// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG0jqXB5Er0Ti5xSLbQk0ATcLuVv0K0PU',
    appId: '1:25567581938:web:e21447f1bf0da44262626b',
    messagingSenderId: '25567581938',
    projectId: 'premiumwork',
    authDomain: 'premiumwork.firebaseapp.com',
    storageBucket: 'premiumwork.firebasestorage.app',
    measurementId: 'G-4C2KPB1Y26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOT1TXZIRg4y0G8uI-Dudgv-O6rQc8iEk',
    appId: '1:25567581938:android:fedc22eeb52d443e62626b',
    messagingSenderId: '25567581938',
    projectId: 'premiumwork',
    storageBucket: 'premiumwork.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgnjNf9MNugZ13RrEogrLzVNn4Lg0xII',
    appId: '1:25567581938:ios:4ba30644ba3001ec62626b',
    messagingSenderId: '25567581938',
    projectId: 'premiumwork',
    storageBucket: 'premiumwork.firebasestorage.app',
    iosBundleId: 'com.premiumwork.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEgnjNf9MNugZ13RrEogrLzVNn4Lg0xII',
    appId: '1:25567581938:ios:4ba30644ba3001ec62626b',
    messagingSenderId: '25567581938',
    projectId: 'premiumwork',
    storageBucket: 'premiumwork.firebasestorage.app',
    iosBundleId: 'com.premiumwork.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG0jqXB5Er0Ti5xSLbQk0ATcLuVv0K0PU',
    appId: '1:25567581938:web:e21447f1bf0da44262626b',
    messagingSenderId: '25567581938',
    projectId: 'premiumwork',
    authDomain: 'premiumwork.firebaseapp.com',
    storageBucket: 'premiumwork.firebasestorage.app',
    measurementId: 'G-4C2KPB1Y26',
  );
} 